# Generated by Django 4.1.7 on 2023-04-17 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_likes_user_likes_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='likes',
            name='id',
        ),
    ]
